# Generated by Django 4.2.1 on 2023-06-05 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='archives/')),
            ],
            options={
                'verbose_name': '- Проект',
                'verbose_name_plural': '- Проекты',
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(verbose_name='Путь')),
                ('error', models.TextField(verbose_name='Ошибка')),
                ('level', models.CharField(max_length=255, verbose_name='Уровень ошибки')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeAnalyzer.archive', verbose_name='Проект')),
            ],
            options={
                'verbose_name': '- Ошибка',
                'verbose_name_plural': '- Ошибки',
            },
        ),
    ]
